### ISSUE TITLE
GameControllerがシンタックスエラーとなってしまうのですがどうすればいいでしょうか？

### ISSUE THREAD

**Issue by nishisyoma** [nishisyoma/mynews#2]

**Comment by hidekazu-yokoi** [comment]
確認少々お待ちください

**Comment by papilioio** [comment]
https://github.com/nishisyoma/mynews/commit/4f4dbacce84437da2299a5ca2715fd8320a4623b
コミットしました。差分を確認してみてください

**Comment by nishisyoma** [comment]
確認しました。ありがとうございます。
